version: "3.8"
services:
  front:
    build: ./
    container_name: front
    volumes:
      - ./src:/app
    working_dir: /app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    