version: "3.8"
services:
  front:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: front
    ports:
      - 80:80
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  default:
    name: aps_default
    external: true
    